import type { Metadata } from "next";
import "@fontsource/roboto";
import "./globals.css";
import OuterWrapper from "./components/OuterWrapper";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <OuterWrapper>{children}</OuterWrapper>
      </body>
    </html>
  );
}

export default RootLayout;
